# Generated by Django 4.2.16 on 2025-02-28 09:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("location", "0018_auto_20230925_2243"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensitizationTraining",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "sensitization_date",
                    models.DateField(
                        verbose_name="Date de la sensibilisation/Formation"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "module_mip",
                                "Module MIP (Mesures d'Inclusion Productive)",
                            ),
                            (
                                "module_mach",
                                "Module MACH (Mesures d'Accompagnement pour le développement du Capital Humain)",
                            ),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Thème",
                    ),
                ),
                (
                    "modules",
                    models.JSONField(
                        blank=True,
                        help_text="Selected modules",
                        null=True,
                        verbose_name="Modules",
                    ),
                ),
                (
                    "facilitator",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Animateur"
                    ),
                ),
                (
                    "male_participants",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Participants Hommes",
                    ),
                ),
                (
                    "female_participants",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Participantes Femmes",
                    ),
                ),
                (
                    "twa_participants",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Participants Twa",
                    ),
                ),
                (
                    "observations",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observations"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="location.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sensibilisation/Formation",
                "verbose_name_plural": "Sensibilisations/Formations",
                "ordering": ["-sensitization_date"],
            },
        ),
    ]
