# Generated by Django 4.2.16 on 2025-02-28 10:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0018_auto_20230925_2243"),
        ("merankabandi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BehaviorChangePromotion",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("report_date", models.DateField(verbose_name="Date de l'activité'")),
                (
                    "male_participants",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Participants Hommes",
                    ),
                ),
                (
                    "female_participants",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Participantes Femmes",
                    ),
                ),
                (
                    "twa_participants",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Participants Twa",
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, null=True, verbose_name="Commentaires"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="location.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promotion du changement de comportement",
                "verbose_name_plural": "Promotion du changement de comportement",
                "ordering": ["-report_date", "location"],
            },
        ),
    ]
