# Generated by Django 4.2.16 on 2025-02-28 11:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0018_auto_20230925_2243"),
        ("merankabandi", "0002_behaviorchangepromotion"),
    ]

    operations = [
        migrations.CreateModel(
            name="MicroProject",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("report_date", models.DateField(verbose_name="Date de l'activité'")),
                (
                    "male_participants",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Participants Hommes",
                    ),
                ),
                (
                    "female_participants",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Participantes Femmes",
                    ),
                ),
                (
                    "twa_participants",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Participants Twa",
                    ),
                ),
                (
                    "agriculture_beneficiaries",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "livestock_goat_beneficiaries",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "livestock_pig_beneficiaries",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "livestock_rabbit_beneficiaries",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "livestock_poultry_beneficiaries",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "livestock_cattle_beneficiaries",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "commerce_services_beneficiaries",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="location.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Micro-projet",
                "verbose_name_plural": "Micro-projets",
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="OtherProjectType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "beneficiary_count",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "microproject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="other_project_types",
                        to="merankabandi.microproject",
                    ),
                ),
            ],
        ),
    ]
