# Generated by Django 4.2.16 on 2025-02-28 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merankabandi", "0003_microproject_otherprojecttype"),
    ]

    operations = [
        migrations.AddField(
            model_name="microproject",
            name="livestock_beneficiaries",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
