# Generated by Django 4.2.16 on 2025-03-03 08:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0018_auto_20230925_2243"),
        ("payroll", "0023_historicalpaymentpoint_payment_method_and_more"),
        ("social_protection", "0014_replace_benefitplan_max_beneficiaries_values"),
        ("merankabandi", "0005_alter_sensitizationtraining_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonetaryTransfer",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("transfer_date", models.DateField(verbose_name="Date des transferts")),
                (
                    "planned_women",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Femmes prévues",
                    ),
                ),
                (
                    "planned_men",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Hommes prévus",
                    ),
                ),
                (
                    "planned_twa",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Twa prévus",
                    ),
                ),
                (
                    "paid_women",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Femmes payées",
                    ),
                ),
                (
                    "paid_men",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Hommes payés",
                    ),
                ),
                (
                    "paid_twa",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Twa payés",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="location.location",
                    ),
                ),
                (
                    "payment_agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payroll.paymentpoint",
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="social_protection.benefitplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transfert Monétaire",
                "verbose_name_plural": "Transferts Monétaires",
                "ordering": ["-transfer_date"],
            },
        ),
    ]
