# Generated by Django 4.2.20 on 2025-04-29 22:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0018_auto_20230925_2243"),
        ("contribution_plan", "0013_alter_contributionplan_date_created_and_more"),
        ("payroll", "0023_historicalpaymentpoint_payment_method_and_more"),
        ("merankabandi", "0007_indicator_section_indicatorachievement_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProvincePaymentPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "payment_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="province_payment_points",
                        to="contribution_plan.paymentplan",
                    ),
                ),
                (
                    "payment_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="province_associations",
                        to="payroll.paymentpoint",
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="province_payment_points",
                        to="location.location",
                    ),
                ),
            ],
            options={
                "db_table": "merankabandi_province_payment_point",
                "unique_together": {("province", "payment_point", "payment_plan")},
            },
        ),
    ]
