# Generated by Django on 2025-01-28
# Materialized views are managed via: python manage.py manage_views --action=create
# They cannot be created in a migration because they reference tables from
# multiple apps (social_protection, individual, payroll, grievance, location)
# that may not be fully migrated yet during initial setup.
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merankabandi', '0009_add_validation_fields'),
    ]

    operations = [
        # No-op: views are created and refreshed via the manage_views command.
        # Run after all migrations complete:
        #   python manage.py manage_views --action=create
    ]
