# Generated by Django 4.2.21 on 2025-05-30 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merankabandi", "0010_create_dashboard_materialized_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="monetarytransfer",
            name="planned_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Montant total prévu à distribuer (BIF)",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Montant prévu",
            ),
        ),
        migrations.AddField(
            model_name="monetarytransfer",
            name="transferred_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Montant effectivement transféré (BIF)",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Montant transféré",
            ),
        ),
    ]
