# Generated by Django 4.2.21 on 2025-06-18 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("merankabandi", "0011_add_amount_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultFrameworkSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("snapshot_date", models.DateTimeField(auto_now_add=True)),
                ("data", models.JSONField()),
                ("document_path", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("FINALIZED", "Finalized"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Result Framework Snapshot",
                "verbose_name_plural": "Result Framework Snapshots",
                "ordering": ["-snapshot_date"],
            },
        ),
        migrations.CreateModel(
            name="IndicatorCalculationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calculation_type",
                    models.CharField(
                        choices=[
                            ("SYSTEM", "System Calculated"),
                            ("MANUAL", "Manual Entry"),
                            ("MIXED", "Mixed System/Manual"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "calculation_method",
                    models.CharField(
                        blank=True,
                        help_text="Method name for system calculations",
                        max_length=100,
                    ),
                ),
                (
                    "calculation_config",
                    models.JSONField(
                        default=dict, help_text="Configuration for calculations"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "indicator",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculation_rule",
                        to="merankabandi.indicator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicator Calculation Rule",
                "verbose_name_plural": "Indicator Calculation Rules",
            },
        ),
    ]
