# Generated by Django 4.2.28 on 2026-03-18 13:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("social_protection", "0022_historicalproject_allows_multiple_enrollments_and_more"),
        ("individual", "0018_alter_groupindividual_role_and_more"),
        ("location", "0019_alter_location_code"),
        ("merankabandi", "0012_resultframeworksnapshot_indicatorcalculationrule"),
    ]

    operations = [
        migrations.CreateModel(
            name="PmtFormula",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "base_score_urban",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "base_score_rural",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "variables",
                    models.JSONField(
                        default=list,
                        help_text="List of {field, weight, category, urban_weight, rural_weight}",
                    ),
                ),
                (
                    "geographic_adjustments",
                    models.JSONField(
                        default=dict,
                        help_text="Map of province_code -> adjustment value",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "PMT Formula",
                "verbose_name_plural": "PMT Formulas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PreCollecte",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("prenom", models.CharField(max_length=255)),
                ("pere", models.CharField(blank=True, default="", max_length=255)),
                ("mere", models.CharField(blank=True, default="", max_length=255)),
                ("ci", models.CharField(blank=True, default="", max_length=50)),
                ("telephone", models.CharField(blank=True, default="", max_length=15)),
                ("sexe", models.CharField(max_length=1)),
                ("mutwa", models.BooleanField(default=False)),
                ("rapatrie", models.BooleanField(default=False)),
                ("age_handicap", models.BooleanField(default=False)),
                (
                    "social_id",
                    models.CharField(
                        blank=True, default="", max_length=14, unique=True
                    ),
                ),
                ("social_id_seq", models.IntegerField(default=0)),
                ("targeting_round", models.IntegerField(default=1)),
                ("kobo_uuid", models.CharField(blank=True, default="", max_length=255)),
                ("device_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("COLLECTED", "Collected"),
                            ("LINKED", "Linked"),
                            ("DELETED", "Deleted"),
                        ],
                        default="COLLECTED",
                        max_length=20,
                    ),
                ),
                ("json_ext", models.JSONField(blank=True, null=True)),
                (
                    "benefit_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="social_protection.benefitplan",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="precollecte_records",
                        to="individual.group",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="precollecte_records",
                        to="location.location",
                    ),
                ),
                (
                    "origin_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="precollecte_origin_records",
                        to="location.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pre-Collecte",
                "verbose_name_plural": "Pre-Collectes",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="SelectionQuota",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("targeting_round", models.IntegerField(default=1)),
                ("quota", models.IntegerField()),
                (
                    "collect_multiplier",
                    models.DecimalField(decimal_places=2, default=2.0, max_digits=4),
                ),
                (
                    "benefit_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="social_protection.benefitplan",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="selection_quotas",
                        to="location.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Selection Quota",
                "verbose_name_plural": "Selection Quotas",
                "ordering": ["benefit_plan", "location"],
                "unique_together": {("benefit_plan", "location", "targeting_round")},
            },
        ),
    ]
