# Generated by Django 4.2.28 on 2026-03-29 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("grievance_social_protection", "__first__"),
        ("individual", "0018_alter_groupindividual_role_and_more"),
        ("location", "0019_alter_location_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("merankabandi", "0013_precollecte_pmtformula_selectionquota"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrievanceTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "assigned_role",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("BLOCKED", "Blocked"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("result", models.JSONField(blank=True, null=True)),
                ("json_ext", models.JSONField(blank=True, null=True)),
                (
                    "assigned_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grievance_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blocked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blocking",
                        to="merankabandi.grievancetask",
                    ),
                ),
            ],
            options={
                "db_table": "merankabandi_grievance_task",
            },
        ),
        migrations.CreateModel(
            name="WorkflowTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("label", models.CharField(max_length=255)),
                (
                    "case_type",
                    models.CharField(db_index=True, default="", max_length=255),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("json_ext", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "merankabandi_workflow_template",
            },
        ),
        migrations.AlterField(
            model_name="behaviorchangepromotion",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="microproject",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="monetarytransfer",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="sensitizationtraining",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.CreateModel(
            name="WorkflowStepTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                ("role", models.CharField(blank=True, max_length=100, null=True)),
                ("is_required", models.BooleanField(default=True)),
                ("condition", models.JSONField(blank=True, null=True)),
                (
                    "action_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("json_ext", models.JSONField(blank=True, null=True)),
                (
                    "workflow_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="merankabandi.workflowtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "merankabandi_workflow_step_template",
                "ordering": ["order"],
                "unique_together": {("workflow_template", "order")},
            },
        ),
        migrations.CreateModel(
            name="RoleAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("role", models.CharField(max_length=100)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("json_ext", models.JSONField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_assignments",
                        to="location.location",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "merankabandi_role_assignment",
            },
        ),
        migrations.CreateModel(
            name="ReplacementRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "replaced_social_id",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("motif", models.TextField(blank=True, null=True)),
                (
                    "relationship",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("new_nom", models.CharField(blank=True, max_length=255, null=True)),
                ("new_prenom", models.CharField(blank=True, max_length=255, null=True)),
                ("new_date_naissance", models.DateField(blank=True, null=True)),
                ("new_sexe", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "new_telephone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("new_cni", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("EXECUTED", "Executed"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("json_ext", models.JSONField(blank=True, null=True)),
                (
                    "new_individual",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replacement_requests_as_new",
                        to="individual.individual",
                    ),
                ),
                (
                    "replaced_individual",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replacement_requests_as_replaced",
                        to="individual.individual",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replacement_requests",
                        to="merankabandi.grievancetask",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replacement_requests",
                        to="grievance_social_protection.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "merankabandi_replacement_request",
            },
        ),
        migrations.CreateModel(
            name="GrievanceWorkflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("json_ext", models.JSONField(blank=True, null=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="merankabandi.workflowtemplate",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to="grievance_social_protection.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "merankabandi_grievance_workflow",
            },
        ),
        migrations.AddField(
            model_name="grievancetask",
            name="step_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="task_instances",
                to="merankabandi.workflowsteptemplate",
            ),
        ),
        migrations.AddField(
            model_name="grievancetask",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflow_tasks",
                to="grievance_social_protection.ticket",
            ),
        ),
        migrations.AddField(
            model_name="grievancetask",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="merankabandi.grievanceworkflow",
            ),
        ),
    ]
