# Generated by Django 4.2.28 on 2026-03-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merankabandi", "0016_drop_ticket_custom_columns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowtemplate",
            name="case_type",
            field=models.CharField(db_index=True, default="", max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="workflowsteptemplate",
            unique_together={("workflow_template", "order")},
        ),
    ]
