# Generated by Django 4.2.28 on 2026-04-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merankabandi", "0016_payment_agency"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentagency",
            name="gateway_config",
            field=models.TextField(
                blank=True,
                default="",
                help_text="JSON configuration for the payment gateway connector (e.g. class path, credentials key)",
            ),
        ),
    ]
