# Generated by Django 4.2.28 on 2026-04-03 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("merankabandi", "0018_communepaymentschedule"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProvincePaymentPoint",
        ),
    ]
