# Generated by Django 4.2.28 on 2026-04-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merankabandi", "0019_remove_province_payment_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="grievancetask",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Display order within workflow"
            ),
        ),
    ]
